"use client";
import Navbar from "@/app/components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "@/app/components/sidebar/Sidebar";
import { Provider, useSelector } from "react-redux";
import store from "@/store";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import Footer from "@/app/components/footer/Footer";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isNavbarOpen, setIsNavbarOpen] = useState(false);

  const toggleNavbar = isOpen => {
    setIsNavbarOpen(isOpen);
  };

  return (
    <html lang="en">
      <Provider store={store}>
        <body className={inter.className}>
          <Theme>
            <div>
              <Navbar toggleNavbar={toggleNavbar} />
              {isNavbarOpen && (
                <div className="bg-gray-400 h-full w-full absolute z-20 opacity-60"></div>
              )}
              <div className="absolute z-30 opacity-90">
                <Sidebar />
              </div>
            </div>
            <main>
              <div className="bg-gray-900">{children}</div>
              <Footer />
            </main>
          </Theme>
        </body>
      </Provider>
    </html>
  );
}
